languages = ['Français', 'English', 'Español', 'Italiano', 'Kreyòl', '中文', 'हिंदी']
translations = {
    'Français': {
        'first_name': 'Prénom',
        'last_name': 'Nom de famille',
        'nam': 'Numéro d\'assurance maladie',
        'card_seq_number': 'Numéro de séquence (deux chiffres sous le nom, ex: 11)',
        'placeholder_first_name': 'Entrez votre prénom',
        'postal_code' : 'Code Postale',
        'cellphone': 'Telephone Mobile',
        'email': 'Email',
        'placeholder_last_name': 'Entrez votre nom de famille',
        'placeholder_nam': 'Format: XXXX 0000 0000',
        'placeholder_card_seq': 'Entrez le numéro de séquence',
        'placeholder_postal_code': 'A0A 0A0',
        'placeholder_cellphone' : '1234567890',
        'placeholder_email': 'test@example.com',
        'start': 'Démarrer',
        'stop': 'Arrêter',
        'status': 'Statut',
        'ready': 'Prêt à démarrer',
        'running': 'En cours...',
        'stopping': 'Arrêt...',
        'error_fields': 'Erreur: Veuillez remplir tous les champs',
        'app_title': 'Recherche Automatique de rendez-vous',
        'language': 'Langue',
        'footer': 'www.meulade.com - Bien tanné de se faire fourrer.',
        'birth_day': 'Jour de naissance',
        'birth_month': 'Mois de naissance',
        'birth_year': 'Année de naissance',
        'placeholder_birth_day': 'JJ',
        'placeholder_birth_month': 'MM',
        'placeholder_birth_year': 'AAAA',
        'sound_notification_1': "Un son vous avertira quand un rendez-vous aura été trouvé,",
        'sound_notification_2': "allumez vos haut parleurs!",
    },
    'English': {
        'first_name': 'First Name',
        'last_name': 'Last Name',
        'nam': 'Health Insurance Number',
        'card_seq_number': 'Card Sequence (two digits under name, ex: 11)',
        'postal_code' : 'Postal Code',
        'cellphone': 'Cellphone',
        'email': 'Email',
        'placeholder_first_name': 'Enter your first name',
        'placeholder_last_name': 'Enter your last name',
        'placeholder_nam': 'Format: XXXX 0000 0000',
        'placeholder_card_seq': 'Enter sequence number',
        'placeholder_postal_code': 'A0A 0A0',
        'placeholder_cellphone' : '1234567890',
        'placeholder_email': 'test@example.com',
        'start': 'Start',
        'stop': 'Stop',
        'status': 'Status',
        'ready': 'Ready to start',
        'running': 'Running...',
        'stopping': 'Stopping...',
        'error_fields': 'Error: Please fill in all fields',
        'app_title': 'RVSQ Appointment Finder',
        'language': 'Language',
        'footer': 'www.meulade.com - Fed up with getting screwed over.',
        'birth_day': 'Birth Day',
        'birth_month': 'Birth Month',
        'birth_year': 'Birth Year',
        'placeholder_birth_day': 'DD',
        'placeholder_birth_month': 'MM',
        'placeholder_birth_year': 'YYYY',
        'sound_notification_1': "A sound will alert you when an appointment is found,",
        'sound_notification_2': "turn on your speakers!",
    },
    'Español': {
        'first_name': 'Nombre',
        'last_name': 'Apellido',
        'nam': 'Número de seguro médico',
        'card_seq_number': 'Número de secuencia (dos dígitos debajo del nombre, ej: 11)',
        'postal_code' : 'Código Postal',
        'placeholder_first_name': 'Ingrese su nombre',
        'placeholder_last_name': 'Ingrese su apellido',
        'placeholder_nam': 'Formato: XXXX 0000 0000',
        'placeholder_card_seq': 'Ingrese el número de secuencia',
        'placeholder_postal_code': 'A0A 0A0',
        'cellphone': 'Teléfono móvil',
        'email': 'Correo electrónico',
        'placeholder_cellphone': '1234567890',
        'placeholder_email': 'test@example.com',
        'start': 'Empezar',
        'stop': 'Detener',
        'status': 'Estado',
        'ready': 'Listo para empezar',
        'running': 'En ejecución...',
        'stopping': 'Deteniendo...',
        'error_fields': 'Error: Por favor complete todos los campos',
        'app_title': 'Buscador de Citas RVSQ',
        'language': 'Idioma',
        'footer': 'www.meulade.com - Hartos de que nos tomen el pelo.',
        'birth_day': 'Día de nacimiento',
        'birth_month': 'Mes de nacimiento',
        'birth_year': 'Año de nacimiento',
        'placeholder_birth_day': 'DD',
        'placeholder_birth_month': 'MM',
        'placeholder_birth_year': 'AAAA',
        'sound_notification_1': "¡Un sonido le avisará cuando se encuentre una cita,",
        'sound_notification_2': "encienda sus altavoces!",
    },
    'Italiano': {
        'first_name': 'Nome',
        'last_name': 'Cognome',
        'nam': 'Numero di assicurazione sanitaria',
        'card_seq_number': 'Numero di sequenza (due cifre sotto il nome, es: 11)',
        'postal_code' : 'Codice Postale',
        'placeholder_first_name': 'Inserisci il tuo nome',
        'placeholder_last_name': 'Inserisci il tuo cognome',
        'placeholder_nam': 'Formato: XXXX 0000 0000',
        'placeholder_postal_code': 'A0A 0A0',
        'placeholder_card_seq': 'Inserisci il numero di sequenza',
        'cellphone': 'Telefono cellulare',
        'email': 'Email',
        'placeholder_cellphone': '1234567890',
        'placeholder_email': 'test@example.com',
        'start': 'Iniziare',
        'stop': 'Arrestare',
        'status': 'Stato',
        'ready': 'Pronto per iniziare',
        'running': 'In esecuzione...',
        'stopping': 'Arrestando...',
        'error_fields': 'Errore: Per favore riempire tutti i campi',
        'app_title': 'Ricerca Appuntamenti RVSQ',
        'language': 'Lingua',
        'footer': 'www.meulade.com - Stufi di essere presi in giro.',
        'birth_day': 'Giorno di nascita',
        'birth_month': 'Mese di nascita',
        'birth_year': 'Anno di nascita',
        'placeholder_birth_day': 'GG',
        'placeholder_birth_month': 'MM',
        'placeholder_birth_year': 'AAAA',
        'sound_notification_1': "Un suono ti avviserà quando viene trovato un appuntamento,",
        'sound_notification_2': "accendi gli altoparlanti!",
    },
    'Kreyòl': {
        'first_name': 'Nonm',
        'last_name': 'Nonm',
        'nam': 'Nonm de sécurité sociale',
        'card_seq_number': 'Nimewo sekans (de chif anba non an, egzanp: 11)',
        'postal_code' : 'kòd postal',
        'placeholder_first_name': 'Antre ouvè ou nonm',
        'placeholder_last_name': 'Antre ouv nonm',
        'placeholder_nam': 'Format: XXXX 0000 0000',
        'placeholder_card_seq': 'Antre séquence',
        'placeholder_postal_code': 'A0A 0A0',
        'cellphone': 'Telefòn mobil',
        'email': 'Imèl',
        'placeholder_cellphone': '1234567890',
        'placeholder_email': 'test@example.com',
        'start': 'Kòmèt',
        'stop': 'Arrest',
        'status': 'Estad',
        'ready': 'Pronto pou kòmèt',
        'running': 'En kouri...',
        'stopping': 'Arrestant...',
        'error_fields': 'Erè: Tanpri plese plè ou tous les champs',
        'app_title': 'Chèchè Randevou RVSQ',
        'language': 'Lang',
        'footer': 'www.meulade.com - Nou bouke ak tout magouy sa yo.',
        'birth_day': 'Jou nesans',
        'birth_month': 'Mwa nesans',
        'birth_year': 'Ane nesans',
        'placeholder_birth_day': 'JJ',
        'placeholder_birth_month': 'MM',
        'placeholder_birth_year': 'AAAA',
        'sound_notification_1': "Yon son pral avèti ou lè nou jwenn yon randevou,",
        'sound_notification_2': "limen bafle ou yo!",
    },
    '中文': {
        'first_name': '名字',
        'last_name': '姓氏',
        'nam': '医疗保险号码',
        'card_seq_number': '卡序列号（姓名下方的两位数字，例：11）',
        'postal_code' : '邮政编码',
        'placeholder_first_name': '输入你的名字',
        'placeholder_last_name': '输入你的姓氏',
        'placeholder_nam': '格式：XXXX 0000 0000',
        'placeholder_card_seq': '输入序列号',
        'placeholder_postal_code': 'A0A 0A0',
        'cellphone': '手机',
        'email': '电子邮件',
        'placeholder_cellphone': '1234567890',
        'placeholder_email': 'test@example.com',
        'start': '开始',
        'stop': '停止',
        'status': '状态',
        'ready': '准备开始',
        'running': '运行中...',
        'stopping': '停止中...',
        'error_fields': '错误：请填写所有字段',
        'app_title': 'RVSQ 预约查找器',
        'language': '语言',
        'footer': 'www.meulade.com - 受够了被欺骗。',
        'birth_day': '出生日',
        'birth_month': '出生月',
        'birth_year': '出生年',
        'placeholder_birth_day': '日',
        'placeholder_birth_month': '月',
        'placeholder_birth_year': '年',
        'sound_notification_1': "找到预约时会有声音提醒，",
        'sound_notification_2': "请打开扬声器！",
    },
    'हिंदी': {
        'first_name': 'नाम',
        'last_name': 'उपनाम',
        'nam': 'आवेदन ंख्या',
        'card_seq_number': 'कार्ड क्रम संख्या (नाम के नीचे दो अं���, उदा: 11)',
        'postal_code' : 'डाक कोड',
        'placeholder_first_name': 'अपना नाम दर्ज करें',
        'placeholder_last_name': 'अपना उपनाम दर्ज करें',
        'placeholder_nam': 'फॉर्मेट: XXXX 0000 0000',
        'placeholder_card_seq': 'क्रमांक दर्ज करें',
        'placeholder_postal_code': 'A0A 0A0',
        'cellphone': 'मोबाइल फोन',
        'email': 'ईमेल',
        'placeholder_cellphone': '1234567890',
        'placeholder_email': 'test@example.com',
        'start': 'सुरु करें',
        'stop': 'रोकें',
        'status': 'सथिति',
        'ready': 'सुरु करने के लिए 準備',
        'running': 'चल रहा है...',
        'stopping': 'रोक रहा है...',
        'error_fields': 'त्रुटि: सभी फ़ील्ड भरें',
        'app_title': 'RVSQ दपॉइंटमेंट फाइंडर',
        'language': 'भाषा',
        'footer': 'www.meulade.com - परेशान हो गए हैं इस धोखाधड़ी से।',
        'birth_day': 'दन्म दिन',
        'birth_month': 'जन्म महीना',
        'birth_year': 'जन्म वर्ष',
        'placeholder_birth_day': 'दिन',
        'placeholder_birth_month': 'महीना',
        'placeholder_birth_year': 'वर्ष',
        'sound_notification_1': "जब अपॉइंटमेंट मिल जाएगा तो एक आवाज़ आपको सूचित करेगी,",
        'sound_notification_2': "अपने स्पीकर चालू करें!",
    }
    # Add other languages here...
}